### ISSUE TITLE
Duplicate websocket events 

### ISSUE THREAD

**Issue by jamesatjaminit** [LeedsRaspJam/Cryptoid-Gui#1]
![image](https://user-images.githubusercontent.com/47297250/149424311-96f863f1-12ba-4ea5-b28e-c8ded90c39b1.png)

**Comment by jamesatjaminit** [comment]
Note: websocket events aren't being sent twice, it's just the way svelte seems to handle stores and subscriptions

**Comment by thinkingsand** [comment]
No longer relevant due to rewrite
